### ISSUE TITLE
Add browser aliases for TVs

### ISSUE THREAD

**Issue by bfanger** [bfanger/tvkit#2]
`--browser="Tizen 5" would be interpreted as "chrome 56"
`--browser="Samsung 2019" would be interpreted as "chrome 63"

https://developer.samsung.com/signage/develop/specifications/web-engine-specifications.html
https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine

**Comment by dahla1973** [comment]
Hi, thanks for your effort. I tried your project with some success but run into a problem on Samung Tizen when first building my Sveltekit project with the static adapter and then converting them with the tvkit build feature: since the Samsung Webapps engine accesses the files as file:// and not through a web server the /:s in relative URLs confuses it so it can't find the Javascript files. Any thoughts on how to solve this? Thanks and happy to support your project if you need

**Comment by bfanger** [comment]
@chipndahla  Setting the [base]https://vitejs.dev/config/shared-options.html#base to `""` in your Vite config might do the trick, but I haven't tested that.

**Comment by bfanger** [comment]
@chipndahla Hmmm,  file urls or any absolute urls for that matter are an issue, i've create  an issue for that:  #7
